# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline
run-name: CI Pipeline by ${{ github.actor }}
on:
  pull_request:
    branches: ["main"]
jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --coverage

  sonarqube:
    needs: check-application
    uses: tarcisio-pereira/user-management-api/actions/workflows/sonar.yml@main
    secrets: inherit

  # lint:
  #   needs: check-application
  #   uses: tarcisio-pereira/user-management-api/actions/workflows/lint.yml@main # Chama o workflow de Lint
  #   secrets: inherit
