name: Super Lint Test

on:
  workflow_call: # Permite que este workflow seja chamado por outro
  inputs:
    config-path:
      required: true
      type: string
jobs:
  lint:
    build:
      name: lint
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: read
        # To report GitHub Actions status checks
        statuses: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # super-linter needs the full git history to get the
            # list of files that changed across commits
            fetch-depth: 0
        - name: Super-linter
          uses: super-linter/super-linter@v7.2.1 # x-release-please-version
          env:
            # To report GitHub Actions status checks
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
